### PR TITLE
Submiting code for review

### PR DESCRIPTION
**Pull request by fedgut**

### CODE REVIEW

**Comment by fedgut** [comment]
Validated in [W3 Validator](https://validator.w3.org/#validate_by_upload)

**Comment by samgaco** [comment]
Hi @fedgut and @jalasem :vulcan_salute: 

### Impressive work so far :clap: just some minor changes before proceeding:

* **mint**, **quickbooks** and **turbotax** should be text, not an image.
* Read about HTML semantic elements and try to implement some on your project. You could use the `<main>` tag for the dominant content of the body, the footer should be used only once, etc.
* Correct the **linters failing checks.**

### That is it! please, commit these changes and submit back for another code review when you are done :muscle: Regards!

**Comment by jalasem** [comment]
@samgaco Please help us out. I'm getting sick of these linter errors and warning

**Comment by jalasem** [comment]
We've run our HTML file through a validator before now with no errors. I just run it again. No errors

**Comment by stratospherique** [comment]
> We've run our HTML file through a validator before now with no errors. I just run it again. No errors

### Now you just need to submit another code review, Don't worry. you have taking care of everything and you guys deserve a :+1: :+1: . It's just to make your project approved. :muscle:

**Pull request merged**
